### ISSUE TITLE
Random Event

### ISSUE THREAD

**Issue by Miningmark** [Krischan-Klug/pocket-pets#32]
**Value Proposition**
**As a** pet lover, 
**I want to** be challenged while caring for my pet, 
**so that** the gameplay excites me even more and the virtual pet care feels more real.

**Description**
![Image](https://github.com/Krischan-Klug/pocket-pets/assets/150810914/a4a96baf-c75d-4a78-9253-8e7fcac5f50a)

**Acceptance Criteria**
- A new random event occurs at least once a day (day circle)
- it explains the event and its consequences (good or bad) 
- the consequence is adapted immediately in the app

**Tasks**
- create feature branch feature/random-events
- create a data base with different events 
- connect to game loop so that a new random event is shown to the user at least once a day
- create a pop up which explain the random event and what its consequences are (e.g. “your pet is sick. you need to pay 100 medical costs”, “A long walk: increases happiness and hunger, but decreases energy.” “A good night's sleep: Increases energy and happiness, while slightly decreasing hunger”). Implement an “OK / confirm” button to the pop up
- the consequences (e.g. loss of money) will be displayed as soon as the user confirms the random event

**Comment by CharlineOe** [comment]
Do I have to accept every challenge or can I decline to participate?

**Comment by CharlineOe** [comment]
But anyhow...nice feature!
